import { TokenKey, Provider, InjectableDef, ScopeId } from '../metadata';
import { InjectorRecord, Injector } from '../registry';
export declare function onAdmission(token: TokenKey, provider: Provider, context: Injector): boolean | void;
export declare function onScopeCheck(definition: InjectableDef<any>, scope: ScopeId, context: Injector): boolean | void;
export declare function onTransientCheck(token: TokenKey, record: InjectorRecord<unknown>, context: Injector): boolean | void;
export declare function runCustomFactory(token: TokenKey, record: InjectorRecord<unknown>, next: () => unknown, context: Injector): () => unknown;
export declare function runBefore(token: TokenKey, record: InjectorRecord<unknown>, context: Injector): void;
export declare function runBeforeAsync(token: TokenKey, record: InjectorRecord<unknown>, context: Injector): Promise<void>;
export declare function runAfter(token: TokenKey, instance: unknown, record: InjectorRecord<unknown>, context: Injector): void;
export declare function runAfterAsync(token: TokenKey, instance: unknown, record: InjectorRecord<unknown>, context: Injector): Promise<void>;
export declare function runError(token: TokenKey, error: unknown, record: InjectorRecord<unknown>, context: Injector): unknown;
export declare function onDispose(token: TokenKey, instance: unknown, context: Injector): Promise<void> | void;
